### PR TITLE
Build and push docker image

### PR DESCRIPTION
**Pull request by AmgadHasan**
Solves https://github.com/theroyallab/tabbyAPI/issues/123 and https://github.com/theroyallab/tabbyAPI/issues/169#issuecomment-2299042703

**Is your pull request related to a problem? Please describe.**
Currently, we have to clone the code and build the docker image. This requires:
1. Docker
2. Building the image (takes a lot of resources)

**Why should this feature be added?**
To make it easier for developers to setup and run tabbyAPI quickly.

**Examples**
Check the published [images](https://github.com/AmgadHasan/tabbyAPI/pkgs/container/tabbyapi/versions) on my fork.

**Additional context**
None

### CODE REVIEW

**Comment by bdashore3** [comment]
@AmgadHasan Did you test this action?

**Comment by AmgadHasan** [comment]
> @AmgadHasan Did you test this action?

The action itself is working, you can check the built and published images on my port.
https://github.com/AmgadHasan/tabbyAPI/pkgs/container/tabbyapi/versions

However, I haven't tested the images yet as I currently don't have access to a gpu.

**Comment by SecretiveShell** [comment]
I tested the image and it works as a drop in replacement in my existing compose file, no changes required compared to the current local build setup.

**Comment by AmgadHasan** [comment]
> I tested the image and it works as a drop in replacement in my existing compose file, no changes required compared to the current local build setup.

Thank you for testing it out. Could you please test again after deleting all docker cache? We just need to confirm that it was using the published image.

**Comment by SecretiveShell** [comment]
I manually stopped and deleted all containers, ran `docker system prune` and then ran `docker-compose up`. The terminal output showed that it was pulling the container and when it started it worked identically to last time - fully functional with the same performance as before.

**Comment by AmgadHasan** [comment]
> I manually stopped and deleted all containers, ran `docker system prune` and then ran `docker-compose up`. The terminal output showed that it was pulling the container and when it started it worked identically to last time - fully functional with the same performance as before.

Thanks!

cc @bdashore3

**Comment by bdashore3** [comment]
If it runs properly, it's good to go.

**Comment by AmgadHasan** [comment]
The github [action](https://github.com/theroyallab/tabbyAPI/actions/runs/10566639525) ran successfully and the logs show that the image was pushed but I can't find it.

Do we need to enable something for the image to show up?

@bdashore3 Did you get any notifications about this?

**Comment by AmgadHasan** [comment]
> The github [action](https://github.com/theroyallab/tabbyAPI/actions/runs/10566639525) ran successfully and the logs show that the image was pushed but I can't find it.
> 
> Do we need to enable something for the image to show up?
> 
> @bdashore3 Did you get any notifications about this?

It could be private and you need to make it public:
> When you first publish a package, the default visibility is private. To change the visibility or set access permissions, see "[Configuring a package's access control and visibility](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility)." You can link a published package to a repository using the user interface or command line. For more information, see "[Connecting a repository to a package](https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package)."

**Comment by bdashore3** [comment]
Fixed. Permissions were broken.

**Pull request merged**
