### PR TITLE
added quadratic sampling

### PR DESCRIPTION
**Pull request by AAbushady**

### CODE REVIEW

**Comment by AAbushady** [comment]
Leaving in draft until this PR
https://github.com/turboderp/exllamav2/pull/317

**Comment by AAbushady** [comment]
How quadratic sampling works can be found here:
https://github.com/oobabooga/text-generation-webui/pull/5403

**Comment by kalomaze** [comment]
https://github.com/theroyallab/tabbyAPI/assets/66376113/e2bbb75b-1e2f-4d37-9643-7f3fe8c3eecd

As you can see here this allows you to scale determinism vs creativity in a way that's not as linear as temperature.

**Comment by test157t** [comment]
image
1 shot examples

**Comment by frammiie** [comment]
Currently not able to generate samples, but based on experience would highly prefer this to be implemented.

**Comment by test157t** [comment]
image
another set, this time i did regens and picked the most avg representative answer from a pool of 5.

**Pull request merged**
